name: 'snowflake_realtime_dbt_prod'
version: '1.0.0'
config-version: 2

profile: 'snowflake_realtime_dbt_prod'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  snowflake_realtime_dbt_prod:
    staging:
      +materialized: view
      +tags: ['staging']
    marts:
      +materialized: table
      +tags: ['marts', 'daily']
